#端口
server:
  port: 8080

spring:
#  profiles:
#    active: @activatedProperties@
  main:
    show-banner: false
hadoop.name-node: hdfs://180.76.166.199:9000
hadoop.namespace: /mydata
#  hadoop:
#    fsUri: hdfs://132.232.44.82:9000



#log日志
logging:
  level:
    com:
      hadoop:
        demo:
          dao: debug
#mybatis-plus
mybatis-plus:
  　　typeAliasesPackage: com.hadoop.demo.entity
  　　mapperLocations: classpath:mapper/*.xml

---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://180.76.166.199:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource